#Requires -Version 5.1
<#
  Generate-RepoMap.ps1 - concise C# signature index for MASLOOPTIMIZER.
  Extracts: namespace/class/interface/struct/enum/record, public+internal
  methods/properties, static events. Output: REPO_MAP.md in project root.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$Root    = Split-Path -Parent $PSScriptRoot
$OutFile = Join-Path $Root 'REPO_MAP.md'
$ExcludeDirs = @('bin','obj','.git','.vs','_build_release','Tools')

function Get-RelativePath {
    param([string]$FullPath)
    return $FullPath.Substring($Root.Length).TrimStart('\','/').Replace('\','/')
}
function Normalize([string]$Text) {
    return ($Text -replace '\s+', ' ').Trim()
}

$typeRegex = [regex]::new('(?m)^[ \t]*(?<mods>(?:(?:public|internal|private|protected|static|sealed|abstract|partial|readonly|ref|unsafe|new)[ \t]+)*)(?<kind>record[ \t]+struct|record[ \t]+class|record|class|interface|struct|enum|namespace)[ \t]+(?<name>[A-Za-z_]\w*)')

$methodRegex = [regex]::new('(?m)^[ \t]*(?<access>public|internal)[ \t]+(?<mods>(?:(?:static|async|override|virtual|abstract|partial|new|unsafe|extern|sealed|required)[ \t]+)*)(?<ret>[A-Za-z_][A-Za-z0-9_<>,\.\[\]\?~() \t]*?)[ \t]+(?<name>[A-Za-z_]\w*(?:[ \t]*<[^()\r\n]*>)?)[ \t]*(?<params>\((?:[^()]|\([^()]*\))*\))\s*(?<term>;|=>|\{|where)')

$ctorRegex = [regex]::new('(?m)^[ \t]*(?<access>public|internal)[ \t]+(?<name>[A-Za-z_]\w*)[ \t]*(?<params>\((?:[^()]|\([^()]*\))*\))\s*(?<term>;|=>|\{|:)')

$eventRegex = [regex]::new('(?m)^[ \t]*(?<access>public|internal)[ \t]+(?<mods>(?:(?:static|new)[ \t]+)*)event[ \t]+(?<ret>[^;\r\n]+?)[ \t]+(?<name>[A-Za-z_]\w*)[ \t]*;')

$propAutoRegex = [regex]::new('(?m)^[ \t]*(?<access>public|internal)[ \t]+(?<mods>(?:(?:static|required|new|virtual|abstract|override|sealed|readonly)[ \t]+)*)(?<ret>[A-Za-z_][A-Za-z0-9_<>,\.\[\]\?~() \t]*?)[ \t]+(?<name>[A-Za-z_]\w*)[ \t]*\{(?<acc>[^{}]*)\}')

$propExprRegex = [regex]::new('(?m)^[ \t]*(?<access>public|internal)[ \t]+(?<mods>(?:(?:static|required|new|virtual|abstract|override|sealed|readonly)[ \t]+)*)(?<ret>[A-Za-z_][A-Za-z0-9_<>,\.\[\]\?~() \t]*?)[ \t]+(?<name>[A-Za-z_]\w*)[ \t]*=>')

$files = Get-ChildItem -Path $Root -Recurse -File -Filter '*.cs' -ErrorAction SilentlyContinue | Where-Object {
    $rel = $_.FullName.Substring($Root.Length).TrimStart('\', '/')
    $parts = $rel -split '[\\/]'
    foreach ($p in $parts) { if ($ExcludeDirs -contains $p) { return $false } }
    return $true
} | Sort-Object FullName

$out = New-Object System.Collections.Generic.List[string]
$out.Add('# REPO_MAP')
$out.Add('')
$out.Add('> Autogenerated signature index for MASLOOPTIMIZER. Source: `Tools/Generate-RepoMap.ps1`.')
$out.Add('> Regenerate: `powershell -NoProfile -ExecutionPolicy Bypass -File .\Tools\Generate-RepoMap.ps1`')
$out.Add('')

foreach ($file in $files) {
    $rel = Get-RelativePath $file.FullName
    $text = [System.IO.File]::ReadAllText($file.FullName)
    $text = [regex]::Replace($text, '(?s)/\*.*?\*/', '')
    $text = [regex]::Replace($text, '(?m)^[ \t]*//.*$', '')

    $items = New-Object System.Collections.Generic.List[object]
    $used  = New-Object 'System.Collections.Generic.HashSet[int]'

    foreach ($m in $typeRegex.Matches($text)) {
        if (-not $used.Add($m.Index)) { continue }
        $kind = $m.Groups['kind'].Value
        $name = $m.Groups['name'].Value
        $mods = Normalize $m.Groups['mods'].Value
        $sig = if ($kind -eq 'namespace') { "namespace $name;" } else { Normalize "$mods $kind $name" }
        $items.Add([pscustomobject]@{ Index = $m.Index; Text = $sig })
    }
    foreach ($m in $eventRegex.Matches($text)) {
        if (-not $used.Add($m.Index)) { continue }
        $sig = Normalize "$($m.Groups['access'].Value) $($m.Groups['mods'].Value)event $($m.Groups['ret'].Value) $($m.Groups['name'].Value);"
        $items.Add([pscustomobject]@{ Index = $m.Index; Text = $sig })
    }
    foreach ($m in $methodRegex.Matches($text)) {
        if (-not $used.Add($m.Index)) { continue }
        $sig = Normalize "$($m.Groups['access'].Value) $($m.Groups['mods'].Value)$($m.Groups['ret'].Value) $($m.Groups['name'].Value)$($m.Groups['params'].Value);"
        $items.Add([pscustomobject]@{ Index = $m.Index; Text = $sig })
    }
    foreach ($m in $ctorRegex.Matches($text)) {
        if (-not $used.Add($m.Index)) { continue }
        $sig = Normalize "$($m.Groups['access'].Value) $($m.Groups['name'].Value)$($m.Groups['params'].Value);"
        $items.Add([pscustomobject]@{ Index = $m.Index; Text = $sig })
    }
    foreach ($m in $propAutoRegex.Matches($text)) {
        if (-not $used.Add($m.Index)) { continue }
        $acc = $m.Groups['acc'].Value
        if ($acc -match '\binit\b') { $accessor = '{ get; init; }' }
        elseif ($acc -match '\bset\b') {
            if ($acc -match '\b(private|protected|internal)[ \t]+set\b') { $accessor = '{ get; }' }
            else { $accessor = '{ get; set; }' }
        }
        else { $accessor = '{ get; }' }
        $sig = Normalize "$($m.Groups['access'].Value) $($m.Groups['mods'].Value)$($m.Groups['ret'].Value) $($m.Groups['name'].Value) $accessor"
        $items.Add([pscustomobject]@{ Index = $m.Index; Text = $sig })
    }
    foreach ($m in $propExprRegex.Matches($text)) {
        if (-not $used.Add($m.Index)) { continue }
        $sig = Normalize "$($m.Groups['access'].Value) $($m.Groups['mods'].Value)$($m.Groups['ret'].Value) $($m.Groups['name'].Value) { get; }"
        $items.Add([pscustomobject]@{ Index = $m.Index; Text = $sig })
    }

    if ($items.Count -eq 0) { continue }

    $out.Add("### $rel")
    $out.Add('```csharp')
    foreach ($it in ($items | Sort-Object Index)) { $out.Add($it.Text) }
    $out.Add('```')
    $out.Add('')
}

$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($OutFile, $out, $utf8)
Write-Host ("REPO_MAP.md generated: {0} bytes, {1} files scanned." -f (Get-Item $OutFile).Length, $files.Count)
